[default]
description = "Default permissions for the plugin"
permissions = ["get_network_state", "list_wifi_networks", "connect_to_wifi", "disconnect_from_wifi", "get_saved_wifi_networks", "delete_wifi_connection", "toggle_network_state"]
